<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ ucfirst($reportType) }} Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #1d003f;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
        }
        .filters {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 30px;
        }
        .filters h3 {
            margin: 0 0 10px 0;
            font-size: 16px;
            color: #1d003f;
        }
        .filter-item {
            margin: 5px 0;
        }
        .filter-label {
            font-weight: bold;
            display: inline-block;
            width: 120px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #1d003f;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .summary {
            background: #e8f5e8;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 30px;
        }
        .summary h3 {
            margin: 0 0 10px 0;
            font-size: 16px;
            color: #1d003f;
        }
        .summary-item {
            margin: 5px 0;
        }
        .summary-label {
            font-weight: bold;
            display: inline-block;
            width: 150px;
        }
        .footer {
            text-align: center;
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ ucfirst($reportType) }} Report</h1>
        <p>Generated on {{ $generatedAt->format('F d, Y \a\t g:i A') }}</p>
        <p>Net On You - Analytics Dashboard</p>
    </div>

    <div class="summary">
        <h3>Report Summary</h3>
        <div class="summary-item">
            <span class="summary-label">Report Type:</span>
            <span>{{ ucfirst($reportType) }}</span>
        </div>
        <div class="summary-item">
            <span class="summary-label">Total Records:</span>
            <span>{{ count($data) }}</span>
        </div>
        <div class="summary-item">
            <span class="summary-label">Generated At:</span>
            <span>{{ $generatedAt->format('F d, Y \a\t g:i A') }}</span>
        </div>
    </div>

    @if(count($data) > 0)
        <table>
            <thead>
                <tr>
                    @foreach(array_keys($data[0]) as $header)
                        <th>{{ ucwords(str_replace('_', ' ', $header)) }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($data as $row)
                    <tr>
                        @foreach($row as $value)
                            <td>
                                @if(is_array($value))
                                    {{ json_encode($value) }}
                                @elseif(is_bool($value))
                                    {{ $value ? 'Yes' : 'No' }}
                                @elseif(is_numeric($value) && strpos($value, '.') !== false)
                                    {{ number_format($value, 2) }}
                                @elseif(is_numeric($value))
                                    {{ number_format($value) }}
                                @else
                                    {{ $value ?? 'N/A' }}
                                @endif
                            </td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; color: #666;">
            <p>No data available for the selected criteria.</p>
        </div>
    @endif

    <div class="footer">
        <p>This report was automatically generated by the Net On You Analytics System.</p>
        <p>For questions or support, please contact the system administrator.</p>
    </div>
</body>
</html>
